### PR TITLE
MNT Standardise modules

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripeltd/product-issues/issues/570

### CODE REVIEW

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
Looks like this one wasn't mentioned in the main issue.

Need to update `startsWith` syntax in workflows

**Comment by emteknetnz** [comment]
Updated

**Comment by GuySartorelli** [comment]
Looks like you forgot to push

**Comment by emteknetnz** [comment]
:)

**Review by GuySartorelli — APPROVED** [review]

**Pull request merged**
