### PR TITLE
fixed unload modal in GridFieldConfigurablePaginator

### PR DESCRIPTION
**Pull request by ivoba**
This fixes the "Are you sure you want to leave the page" modal popping up when using the GridFieldConfigurablePaginator and paginating to next page with merging some changes from upstream GridFieldPaginator.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Thanks @ivoba for the contribution! I've noticed this too but I haven't had the time to go looking into it 😖 . The test failures are a configuration issue and don't appear to be related to this PR. 

Could you please explain a little about why this fix works?

Additionally the branch you've submitted this to means that it'll be released in the next __major__ release of this module (4.0.0). Would you like to re-target this fix at the `3.0` branch? Then we can release it in the next patch version of this module (3.2.2 assuming you're up to date 😉 ).

**Comment by ivoba** [comment]
@ScopeyNZ i will open a new PR for 3.0.

The upstream change can be found here:
https://github.com/silverstripe/silverstripe-framework/commit/9f5b0086cb1a0259c5c87ea205390c5e69dcae90#diff-a47099327fba1ef78df01fae3192f0ee

**Comment by ScopeyNZ** [comment]
Thanks. I'll close this PR as we'll just merge up the other.

**Comment by ivoba** [comment]
New one is here:
https://github.com/symbiote/silverstripe-gridfieldextensions/pull/287

**Pull request closed without merging**
