### PR TITLE
FIX #309 Support ManyManyThroughList in EditableColumns

### LINKED ISSUE #309: GridFieldEditableColumns does not work with ManyManyThroughList
I just tried to substitute the two occurrences of `$list instanceof ManyManyList` with `($list instanceof ManyManyList || $list instanceof ManyManyThroughList)` but it does not seem to work properly.

Let's pretend to have the following data model:
```php
class Team extends DataObject
{
    private static $many_many = [
        "Supporters" => [
            'through' => TeamSupporter::class,
            'from' => 'Team',
            'to' => 'Supporter',
        ]
    ];
}
class Supporter extends DataObject
{
    private static $belongs_many_many = [
        'Supports' => Team::class,
    ];
}
class TeamSupporter extends DataObject
{
    private static $db = [
        'SomeData' => 'Varchar(10)',
    ];

    private static $has_one = [
        'Team' => Team::class,
        'Supporter' => Supporter::class,
    ];
}
```

With the following code in `Team::getCMSFields` (that works properly when `SomeData` is defined as `$many_many_extraFields`), I am able to change it (I see the new value in the database) but the form field element is not properly populated (it is always empty):
```php
$config->getComponent>ByType(GridFieldEditableColumns::class)->setDisplayFields([
    'SomeData' => 'A really useful field',
]);
```

With the following code, the form field is properly populated but it is turned readonly:
```php
$config->getComponent>ByType(GridFieldEditableColumns::class)->setDisplayFields([
    'TeamSupporter.SomeData' => 'A really useful field',
]);
```

Unfortunately I need to use an explicit through relation to be able to `populateDefaults()` the extra fields and add some calculated field. If anyone has a better idea I'm all ears.

### PR DESCRIPTION
**Pull request by ntd**
The ManyManyThrough fields must be specified without comma, hence its
name must be unique in the joined set of fields. For example, given the
following DataObjects:
```
class Team extends DataObject
{
    private static $many_many = [
        "Supporters" => [
            'through' => TeamSupporter::class,
            'from' => 'Team',
            'to' => 'Supporter',
        ]
    ];
}
class Supporter extends DataObject
{
    private static $belongs_many_many = [
        'Supports' => Team::class,
    ];
}
class TeamSupporter extends DataObject
{
    private static $db = [
        'Ranking' => 'Int',
    ];
    private static $has_one = [
        'Team' => Team::class,
        'Supporter' => Supporter::class,
    ];
}
```
you should refer to the ranking field with `Ranking`, not with
`TeamSupporter.Ranking`.

### CODE REVIEW

**Comment by nyeholt** [comment]
Hi Nicola, does https://github.com/symbiote/silverstripe-gridfieldextensions/pull/294/files fix your issue too? I'm looking to merge that in as it also fixes an issue with the way loadDataFrom executes during save, but it may also fix your problem if you're able to check and confirm for me?

**Comment by ntd** [comment]
Hi @nyeholt,

unfortunately I am still unable to edit my extra fields. For your convenience I paste here the full-blown code that I used for testing.
The data model is the classic Team-Supporter relation and I want to edit the rankings.

```php
use SilverStripe\Admin\ModelAdmin;
use SilverStripe\Forms\GridField\GridFieldConfig;
use SilverStripe\Forms\GridField\GridFieldAddNewButton;
use SilverStripe\Forms\GridField\GridFieldButtonRow;
use SilverStripe\Forms\GridField\GridFieldDetailForm;
use SilverStripe\Forms\NumericField;
use SilverStripe\Forms\ReadonlyField;
use SilverStripe\ORM\DataObject;
use Symbiote\GridFieldExtensions\GridFieldEditableColumns;

class TestAdmin extends ModelAdmin
{
    private static $url_segment = 'editable-test';
    private static $managed_models = [
        Team::class,
    ];
}

class Team extends DataObject
{
    private static $db = [ 'TeamName' => 'Varchar(100)' ];
    private static $summary_fields = [ 'TeamName' ];
    private static $many_many = [
        'Supporters' => [
            'through' => TeamSupporter::class,
            'from' => 'Team',
            'to' => 'Supporter',
        ]
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $grid = $fields->fieldByName('Root.Supporters.Supporters');
        if ($grid) {
            // Needed: Readonly team + Readonly supporter + Editable ranking

            // (1) Implicit scope: ('none') + Editable supporter + ('none')
            //$display = [
            //    'TeamName' => 'Team',
            //    'SupporterName' => 'Supporter',
            //    'Ranking' => 'Ranking',
            //];

            // (2) Explicit scope: Readonly team + Editable supporter + Readonly ranking
            //$display = [
            //    'TeamSupporter.Team.TeamName' => 'Team',
            //    'SupporterName' => 'Supporter',
            //    'TeamSupporter.Ranking' => 'Ranking',
            //];

            // (3) Handcrafted: Readonly team + Readonly supporter + Editable ranking
            //     Almost there *but* in this case the rankings are not
            //     properly saved!
            $display = [
                'TeamSupporter.Team.TeamName' => 'Team',
                'SupporterName' => [
                    'title' => 'Supporter',
                    'field' => ReadonlyField::class,
                ],
                'TeamSupporter.Ranking' => [
                    'title' => 'Supporter',
                    'field' => NumericField::class,
                ],
            ];

            $config = GridFieldConfig::create()
                ->addComponent(new GridFieldButtonRow('before'))
                ->addComponent(new GridFieldAddNewButton('buttons-before-left'))
                ->addComponent(new GridFieldEditableColumns())
                ->addComponent(new GridFieldDetailForm(null, false, true));
            $config->getComponentByType(GridFieldEditableColumns::class)
                ->setDisplayFields($display);
            $grid->setConfig($config);
        }

       return $fields;
    }
}

class Supporter extends DataObject
{
    private static $db = [ 'SupporterName' => 'Varchar(100)' ];
    private static $belongs_many_many = [ 'Supports' => Team::class ];
    private static $summary_fields = [ 'SupporterName' ];
}

class TeamSupporter extends DataObject
{
    private static $db = [ 'Ranking' => 'Int' ];
    private static $has_one = [
        'Team' => Team::class,
        'Supporter' => Supporter::class,
    ];
}
```

**Comment by sminnee** [comment]
It's possible that you also need this unmerged change, @ntd, which I pull into my project via composer-patches https://github.com/silverstripe/silverstripe-framework/pull/9192

I can't recall if it was only needed for detail forms or for editable gridfields too, sorry. But give it a go, maybe?

**Comment by ntd** [comment]
Yessss, thank you @sminnee: your PR fixes the issue.

**Pull request closed without merging**
