### PR TITLE
FIX Respect default sort array in GridFieldOrderableRows

### LINKED ISSUE #324: GridFieldOrderableRows does not support secondary or default sort fields.
I frequently have orderable objects which should have a default sort order, but option for manually overriding. So the object will have something like:

```php
private static $default_sort = 'Sort ASC, Title ASC`;
```

With the `GridFieldOrderableRows` component added, only the sort column managed by the component itself is considered in the CMS display of the items. If no values have been set in the sort field they display unsorted in whichever order SQL decides to show them. (Mostly just ordered by id).

The component offers a getter and setter for `$extraSortFields` but these are applied as higher priority sorts than the managed sort column. What I'm looking for is setting sorts with a lower priority than the managed sort column, preferably making use of the defaults set elsewhere.

PRs
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/325
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/329
- https://github.com/symbiote/silverstripe-gridfieldextensions/pull/349

### PR DESCRIPTION
**Pull request by vinstah**

### CODE REVIEW

**Comment by vinstah** [comment]
https://github.com/symbiote/silverstripe-gridfieldextensions/issues/324 also touches on this

**Review by GuySartorelli — CHANGES_REQUESTED** [review]
If the default sort is an array, that means there are multiple fields in cascading priority by which the list should be sorted. We should respect that instead of just grabbing the top one and discarding the rest.

**Comment by GuySartorelli** [comment]
@vinstah are you interested in making the change I've requested?

**Review by bclegaspi — APPROVED** [review]
Can these be merged already please? thank you

**Comment by GuySartorelli** [comment]
@bclegaspi There are requested changes which have not been made. The PR will not be merged in its current state. If @vinstah makes the requested changes it can be merged - otherwise if you want to create a new PR with the requested changes, that new PR can be reviewed and merged if it resolves the issue and complies with best practices.

**Comment by vinstah** [comment]
Hi have been a bit busy lately, have been thinking about the change but just haven't implemented yet, hoping to get some free time in the next couple of weeks

**Comment by emteknetnz** [comment]
Closed in favor of https://github.com/symbiote/silverstripe-gridfieldextensions/pull/361

**Pull request closed without merging**
