### PR TITLE
Updating namespacing to reflect SS Australia

### PR DESCRIPTION
**Pull request by jackoconnor21**
Extending my last PR to include updated name spaces.

### CODE REVIEW

**Comment by nyeholt** [comment]
Build's failing because GridFieldAddNewMultiClassTest.php is still referencing SilverStripe\ - I think that's all that's needed

**Comment by jackoconnor21** [comment]
I have amended the namespace references

**Comment by nyeholt** [comment]
https://travis-ci.org/silverstripe-australia/silverstripe-gridfieldextensions/jobs/209404670#L257

**Comment by robbieaverill** [comment]
This PR isn't relevant any more. Were there other changes than the namespacing in this?

**Pull request closed without merging**
