### PR TITLE
Fix "+" icon in add new inline button

### PR DESCRIPTION
**Pull request by DrMartinGonzo**

### CODE REVIEW

**Comment by robbieaverill** [comment]
Do you need this change in the current 3.x release line of this module?

**Comment by DrMartinGonzo** [comment]
As you see fit 👍 
I fixed it on my install via css for the time being.

**Comment by robbieaverill** [comment]
Yeah let's target 3.1 - I'll rebase this branch for you

**Comment by robbieaverill** [comment]
Thanks!

**Pull request merged**
