### PR TITLE
SS4 upgrade fixes.

### PR DESCRIPTION
**Pull request by mfendeksilverstripe**
* fixed incorrect reference to `Versioned` class
* fixed incorrect assumption that class names are the same as table names
* GridField reload action no longer triggers the change event as the changes are automatically saved by reorder action

As a result of these fixes this component is finally working with versioned items in the GridField.

### CODE REVIEW

**Comment by mfendeksilverstripe** [comment]
@dhensby Original code contains this:

```
$class = $list->dataClass();
if ($class == $this->getSortTable($list)) {
```

This doesn't work for any object that has class different from table name, which in SS4 is quite common. Of course, the issue is "only" with `Versioned` items as the `if` statement is used to detect `Versioned`.

The JS reformatting is a reasonable change requirement, I'll have a look at it on the next Hackday.

**Comment by mfendeksilverstripe** [comment]
@dhensby I reverted the JS formatting changes. The functional JS changes should be much more clear now. Please review.

**Comment by robbieaverill** [comment]
@mfendeksilverstripe sorry but would you mind rebasing onto 3.1, which is the latest suitable SS4 branch? Thanks :)

**Comment by dhensby** [comment]
merges cleanly into 3.1 - no rebase needed :)

**Pull request merged**
