### PR TITLE
Merge up: 1.5 -> 2.0 -> 2 -> master

### PR DESCRIPTION
**Pull request by robbieaverill**
This PR is a merge up basically from having released a patch version in 1.5.x and 2.0.x, but since it also includes updating the configurable paginator for SS4 I didn't want to push it directly without review.

### CODE REVIEW

**Comment by robbieaverill** [comment]
The test failure is fixed by #209

**Comment by nyeholt** [comment]
I think merging in Naomi's CSS updates has created a conflict - are you able to check ?

**Comment by robbieaverill** [comment]
Thanks @nyeholt - I've merged upstream over the top

**Comment by dhensby** [comment]
So I've gone over this and re-merged up. We're having problems with PHPUnit generating mocks which are compatible with splat operators `Injectable::create(...$arguments)`... I'm not sure how or if we can resolve this...

**Comment by dhensby** [comment]
OK - I've checked locally and I don't have this problem, the method signature is correct :/

**Comment by dhensby** [comment]
Issue was that it's using phpunit 3.7 8-|

update require-dev and we are good.

**Pull request merged**
